### ISSUE TITLE
Circular dependency on `docker-compose pull`

### ISSUE THREAD

**Issue by viktorsmari** [thurloat/docker-compose-sentry#3]
In a fresh repo and performing:

`docker-compose pull`

I get:

> ERROR: Circular dependency between letsencrypt and nginx and sentry-web and sentry-cron

docker-compose version 1.9.0, build 2585387
Docker version 17.05.0-ce-rc3, build 90d35ab

**Comment by thurloat** [comment]
I wonder if it's the link between nginx -> sentry_web, if you're still experiencing this -- can you remove that dependency and see if it stops complaining?

eyeballing the dependency chain, it does seem reasonable though.
